using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using ZooFeeding2.Models;

namespace ZooFeeding2.DAL
{
    public class ZooInitializer : DropCreateDatabaseAlways<ZooContext>
    {
        protected override void Seed(ZooContext context)
        {
            var animals = new List<Animal>
            {
                new Animal { AnimalName="African Bullfrog"},
                new Animal { AnimalName="African Crested Porcupine"},
                new Animal { AnimalName="African Lungfish"},
                new Animal { AnimalName="African Pygmy Hedgehog"},
                new Animal { AnimalName="African Red-Billed Hornbill"},
                new Animal { AnimalName="African Rock Python"},
                new Animal { AnimalName="African Slender-Snouted Crocodile"},
                new Animal { AnimalName="African Spurred Tortoise"},
                new Animal { AnimalName="African Wild Dog"},
                new Animal { AnimalName="Allen's Swamp Monkey"},
                new Animal { AnimalName="American Beaver" },
                new Animal { AnimalName="American Black Bear" },
                new Animal { AnimalName="Amur Leopard" },
                new Animal { AnimalName="Amur Tiger" },
                new Animal { AnimalName="Arrau Turtle" },
                new Animal { AnimalName="Asian Elephant" },
                new Animal { AnimalName="Austraillian Walking Stick" },
                new Animal { AnimalName="Bald Eagle" },
                new Animal { AnimalName="Black Howler Monkey" },
                new Animal { AnimalName="Black Rhinoceros" },
                new Animal { AnimalName="Blue and Gold Macaw" },
                new Animal { AnimalName="Blue-Streaked Lory" },
                new Animal { AnimalName="Bobcat" },
                new Animal { AnimalName="Bontebok" },
                new Animal { AnimalName="Bufflehead" },
                new Animal { AnimalName="Bull Trout" },
                new Animal { AnimalName="Burmese Python" },
                new Animal { AnimalName="California Condor" },
                new Animal { AnimalName="Curacal" },
                new Animal { AnimalName="Cattle Egret" },
                new Animal { AnimalName="Cheetah" },
                new Animal { AnimalName="Chimpanzee" },
                new Animal { AnimalName="Cinnamon Teal" },
                new Animal { AnimalName="Coho Salmon" },
                new Animal { AnimalName="Colombus Monkey" },
                new Animal { AnimalName="Common Emperor Scorpion" },
                new Animal { AnimalName="Cotton Top Tamarin" },
                new Animal { AnimalName="Cougar" },
                new Animal { AnimalName="De Brazza's Monkey" },
                new Animal { AnimalName="Desert Tortoise" },
                new Animal { AnimalName="Dwarf Caimon" },
                new Animal { AnimalName="Dwarf Mongoose" },
                new Animal { AnimalName="Egyptian Fruit Bat" },
                new Animal { AnimalName="Emerald Starling" },
                new Animal { AnimalName="Emerald Tree Boa" },
                new Animal { AnimalName="Ferret" },
                new Animal { AnimalName="Giant African Millipede" },
                new Animal { AnimalName="Giraffe" },
                new Animal { AnimalName="Golden Eagle" },
                new Animal { AnimalName="Golden-Breasted Starling" },
                new Animal { AnimalName="Grey Gull" },
                new Animal { AnimalName="Hadada Ibis" },
                new Animal { AnimalName="Hamerkop" },
                new Animal { AnimalName="Harbor Seal" },
                new Animal { AnimalName="Harris Hawk" },
                new Animal { AnimalName="Hippopotamus" },
                new Animal { AnimalName="Hooded Vulture" },
                new Animal { AnimalName="Hottentot Teal" },
                new Animal { AnimalName="Humboldt Penguin" },
                new Animal { AnimalName="Inca Tern" },
                new Animal { AnimalName="Indian Runner Duck" },
                new Animal { AnimalName="Kinkajoo" },
                new Animal { AnimalName="Lesser Flamingo" },
                new Animal { AnimalName="Lion" },
                new Animal { AnimalName="Madagascar Hissing Cockroach" },
                new Animal { AnimalName="Malagen Sun Bear" },
                new Animal { AnimalName="Mandrill" },
                new Animal { AnimalName="Mexican Red-Kneed Tarantula" },
                new Animal { AnimalName="Naked Mole Rat" },
                new Animal { AnimalName="Nankin Chicken" },
                new Animal { AnimalName="Nigerian Dwarf Goat" },
                new Animal { AnimalName="North American River Otter" },
                new Animal { AnimalName="North Sulawesi Barbirusa" },
                new Animal { AnimalName="Northen Pintail" },
                new Animal { AnimalName="Nothern Shoveler" },
                new Animal { AnimalName="Old World Rabbit" },
                new Animal { AnimalName="Orangutan" },
                new Animal { AnimalName="Oriole Warbler" },
                new Animal { AnimalName="Ornate Monitor Lizard" },
                new Animal { AnimalName="Pacu" },
                new Animal { AnimalName="Philippine Sailfin Lizard" },
                new Animal { AnimalName="Polar Bear" },
                new Animal { AnimalName="Pygmy Goat" },
                new Animal { AnimalName="Pygora Goat" },
                new Animal { AnimalName="Rainbow Trout" },
                new Animal { AnimalName="Red-Bellied Piranha" },
                new Animal { AnimalName="Red-Crested Pochard" },
                new Animal { AnimalName="Red Tailed Hawk" },
                new Animal { AnimalName="Redhead" },
                new Animal { AnimalName="Ringtail" },
                new Animal { AnimalName="Rocky Mountain Goat" },
                new Animal { AnimalName="Rodrigues Flying Fox" },
                new Animal { AnimalName="Sacred Ibis" },
                new Animal { AnimalName="Southern Ground Hornbill" },
                new Animal { AnimalName="Southern Masked Weaver" },
                new Animal { AnimalName="Southern Sea Otter" },
                new Animal { AnimalName="Speakled Mousebird" },
                new Animal { AnimalName="Speke's Gazelle" },
                new Animal { AnimalName="Straw-Colored Fruit Bat" },
                new Animal { AnimalName="Turkey Vulture" },
                new Animal { AnimalName="Veiled Chamelion" },
                new Animal { AnimalName="Violet-Backed Starling" },
                new Animal { AnimalName="Visayan Warty Pig" },
                new Animal { AnimalName="Western Painted Turtle" },
                new Animal { AnimalName="White Sturgeon" },
                new Animal { AnimalName="White Cheeked Gibbon" },
                new Animal { AnimalName="White Faced Saki Monkey" },
                new Animal { AnimalName="White Faced Whistling Duck" },
                new Animal { AnimalName="Wood Duck" }
            };

            animals.ForEach(a => context.Animals.Add(a));
            context.SaveChanges();

            var foods = new List<Food>
            {
                new Food { FoodName="Dry Cat Food"},
                new Food { FoodName="Fish"},
                new Food { FoodName="Fruit"},
                new Food { FoodName="Hay"},
                new Food { FoodName="Insects"},
                new Food { FoodName="Meat"},
                new Food { FoodName="Monkey Chow"},
                new Food { FoodName="Plants"},
                new Food { FoodName="Rodents"},
                new Food { FoodName="Vegetables"}
            };

            foods.ForEach(f => context.Foods.Add(f));
            context.SaveChanges();

            var relationships = new List<Relationship>
            {
                new Relationship { AnimalId=1, FoodId=5},
                new Relationship { AnimalId=2, FoodId=8},
                new Relationship { AnimalId=3, FoodId=9},
                new Relationship { AnimalId=3, FoodId=5},
                new Relationship { AnimalId=3, FoodId=2},
                new Relationship { AnimalId=4, FoodId=1},
                new Relationship { AnimalId=4, FoodId=5},
                new Relationship { AnimalId=5, FoodId=3},
                new Relationship { AnimalId=5, FoodId=8},
                new Relationship { AnimalId=6, FoodId=9},
                new Relationship { AnimalId=7, FoodId=2},
                new Relationship { AnimalId=7, FoodId=9},
                new Relationship { AnimalId=8, FoodId=4},
                new Relationship { AnimalId=8, FoodId=8},
                new Relationship { AnimalId=9, FoodId=7},
                new Relationship { AnimalId=10, FoodId=7},
                new Relationship { AnimalId=10, FoodId=3},
                new Relationship { AnimalId=10, FoodId=10},
                new Relationship { AnimalId=7, FoodId=6},
                new Relationship { AnimalId=11, FoodId=3},
                new Relationship { AnimalId=11, FoodId=4},
                new Relationship { AnimalId=11, FoodId=1},
                new Relationship { AnimalId=11, FoodId=7},
                new Relationship { AnimalId=11, FoodId=10},
                new Relationship { AnimalId=12, FoodId=2},
                new Relationship { AnimalId=12, FoodId=3},
                new Relationship { AnimalId=12, FoodId=6},
                new Relationship { AnimalId=12, FoodId=10},
                new Relationship { AnimalId=13, FoodId=9},
                new Relationship { AnimalId=14, FoodId=9},
                new Relationship { AnimalId=13, FoodId=6},
                new Relationship { AnimalId=14, FoodId=6},
                new Relationship { AnimalId=15, FoodId=3},
                new Relationship { AnimalId=15, FoodId=8},
                new Relationship { AnimalId=15, FoodId=9},
                new Relationship { AnimalId=15, FoodId=4},
                new Relationship { AnimalId=16, FoodId=3},
                new Relationship { AnimalId=16, FoodId=4},
                new Relationship { AnimalId=17, FoodId=8},
                new Relationship { AnimalId=18, FoodId=2},
                new Relationship { AnimalId=18, FoodId=9},
                new Relationship { AnimalId=19, FoodId=3},
                new Relationship { AnimalId=19, FoodId=7},
                new Relationship { AnimalId=19, FoodId=10},
                new Relationship { AnimalId=20, FoodId=8},
                new Relationship { AnimalId=21, FoodId=3},
                new Relationship { AnimalId=21, FoodId=8},
                new Relationship { AnimalId=21, FoodId=10},
                new Relationship { AnimalId=22, FoodId=3},
                new Relationship { AnimalId=22, FoodId=10},
                new Relationship { AnimalId=23, FoodId=2},
                new Relationship { AnimalId=23, FoodId=6},
                new Relationship { AnimalId=23, FoodId=9},
                new Relationship { AnimalId=24, FoodId=8},
                new Relationship { AnimalId=25, FoodId=5},
                new Relationship { AnimalId=26, FoodId=2},
                new Relationship { AnimalId=27, FoodId=9},
                new Relationship { AnimalId=28, FoodId=6},
                new Relationship { AnimalId=29, FoodId=6},
                new Relationship { AnimalId=30, FoodId=5},
                new Relationship { AnimalId=31, FoodId=1},
                new Relationship { AnimalId=31, FoodId=6},
                new Relationship { AnimalId=32, FoodId=3},
                new Relationship { AnimalId=32, FoodId=5},
                new Relationship { AnimalId=32, FoodId=6},
                new Relationship { AnimalId=32, FoodId=7},
                new Relationship { AnimalId=32, FoodId=10},
                new Relationship { AnimalId=33, FoodId=5},
                new Relationship { AnimalId=33, FoodId=8},
                new Relationship { AnimalId=34, FoodId=2},
                new Relationship { AnimalId=35, FoodId=7},
                new Relationship { AnimalId=36, FoodId=5},
                new Relationship { AnimalId=37, FoodId=5},
                new Relationship { AnimalId=37, FoodId=3},
                new Relationship { AnimalId=38, FoodId=6},
                new Relationship { AnimalId=39, FoodId=7},
                new Relationship { AnimalId=39, FoodId=3},
                new Relationship { AnimalId=39, FoodId=10},
                new Relationship { AnimalId=40, FoodId=3},
                new Relationship { AnimalId=40, FoodId=10},
                new Relationship { AnimalId=41, FoodId=2},
                new Relationship { AnimalId=41, FoodId=9},
                new Relationship { AnimalId=42, FoodId=1},
                new Relationship { AnimalId=42, FoodId=9},
                new Relationship { AnimalId=42, FoodId=10},
                new Relationship { AnimalId=43, FoodId=3},
                new Relationship { AnimalId=44, FoodId=3},
                new Relationship { AnimalId=44, FoodId=5},
                new Relationship { AnimalId=45, FoodId=9},
                new Relationship { AnimalId=46, FoodId=1},
                new Relationship { AnimalId=46, FoodId=3},
                new Relationship { AnimalId=46, FoodId=10},
                new Relationship { AnimalId=47, FoodId=3},
                new Relationship { AnimalId=47, FoodId=10},
                new Relationship { AnimalId=48, FoodId=8},
                new Relationship { AnimalId=49, FoodId=6},
                new Relationship { AnimalId=50, FoodId=5},
                new Relationship { AnimalId=50, FoodId=3},
                new Relationship { AnimalId=51, FoodId=2},
                new Relationship { AnimalId=52, FoodId=5},
                new Relationship { AnimalId=53, FoodId=2},
                new Relationship { AnimalId=54, FoodId=2},
                new Relationship { AnimalId=55, FoodId=6},
                new Relationship { AnimalId=56, FoodId=8},
                new Relationship { AnimalId=57, FoodId=6},
                new Relationship { AnimalId=58, FoodId=5},
                new Relationship { AnimalId=58, FoodId=8},
                new Relationship { AnimalId=59, FoodId=2},
                new Relationship { AnimalId=60, FoodId=2},
                new Relationship { AnimalId=61, FoodId=1},
                new Relationship { AnimalId=61, FoodId=10},
                new Relationship { AnimalId=62, FoodId=3},
                new Relationship { AnimalId=62, FoodId=5},
                new Relationship { AnimalId=63, FoodId=8},
                new Relationship { AnimalId=64, FoodId=6},
                new Relationship { AnimalId=65, FoodId=8},
                new Relationship { AnimalId=66, FoodId=3},
                new Relationship { AnimalId=66, FoodId=6},
                new Relationship { AnimalId=67, FoodId=3},
                new Relationship { AnimalId=67, FoodId=7},
                new Relationship { AnimalId=67, FoodId=5},
                new Relationship { AnimalId=67, FoodId=10},
                new Relationship { AnimalId=68, FoodId=5},
                new Relationship { AnimalId=69, FoodId=10},
                new Relationship { AnimalId=70, FoodId=5},
                new Relationship { AnimalId=71, FoodId=8},
                new Relationship { AnimalId=70, FoodId=10},
                new Relationship { AnimalId=72, FoodId=2},
                new Relationship { AnimalId=72, FoodId=5},
                new Relationship { AnimalId=73, FoodId=3},
                new Relationship { AnimalId=73, FoodId=4},
                new Relationship { AnimalId=73, FoodId=10},
                new Relationship { AnimalId=74, FoodId=5},
                new Relationship { AnimalId=74, FoodId=8},
                new Relationship { AnimalId=75, FoodId=5},
                new Relationship { AnimalId=75, FoodId=8},
                new Relationship { AnimalId=76, FoodId=3},
                new Relationship { AnimalId=76, FoodId=10},
                new Relationship { AnimalId=77, FoodId=3},
                new Relationship { AnimalId=77, FoodId=8},
                new Relationship { AnimalId=78, FoodId=5},
                new Relationship { AnimalId=79, FoodId=9},
                new Relationship { AnimalId=80, FoodId=10},
                new Relationship { AnimalId=81, FoodId=2},
                new Relationship { AnimalId=81, FoodId=3},
                new Relationship { AnimalId=81, FoodId=10},
                new Relationship { AnimalId=82, FoodId=6},
                new Relationship { AnimalId=83, FoodId=8},
                new Relationship { AnimalId=84, FoodId=8},
                new Relationship { AnimalId=85, FoodId=5},
                new Relationship { AnimalId=85, FoodId=8},
                new Relationship { AnimalId=86, FoodId=2},
                new Relationship { AnimalId=87, FoodId=8},
                new Relationship { AnimalId=88, FoodId=9},
                new Relationship { AnimalId=89, FoodId=5},
                new Relationship { AnimalId=89, FoodId=8},
                new Relationship { AnimalId=90, FoodId=3},
                new Relationship { AnimalId=90, FoodId=5},
                new Relationship { AnimalId=90, FoodId=9},
                new Relationship { AnimalId=91, FoodId=8},
                new Relationship { AnimalId=92, FoodId=3},
                new Relationship { AnimalId=92, FoodId=10},
                new Relationship { AnimalId=93, FoodId=5},
                new Relationship { AnimalId=94, FoodId=5},
                new Relationship { AnimalId=95, FoodId=5},
                new Relationship { AnimalId=96, FoodId=2},
                new Relationship { AnimalId=97, FoodId=3},
                new Relationship { AnimalId=97, FoodId=8},
                new Relationship { AnimalId=98, FoodId=8},
                new Relationship { AnimalId=99, FoodId=3},
                new Relationship { AnimalId=100, FoodId=6},
                new Relationship { AnimalId=100, FoodId=3},
                new Relationship { AnimalId=100, FoodId=10},
                new Relationship { AnimalId=101, FoodId=5},
                new Relationship { AnimalId=102, FoodId=3},
                new Relationship { AnimalId=102, FoodId=5},
                new Relationship { AnimalId=103, FoodId=10},
                new Relationship { AnimalId=104, FoodId=5},
                new Relationship { AnimalId=104, FoodId=8},
                new Relationship { AnimalId=105, FoodId=2},
                new Relationship { AnimalId=106, FoodId=7},
                new Relationship { AnimalId=106, FoodId=3},
                new Relationship { AnimalId=106, FoodId=10},
                new Relationship { AnimalId=107, FoodId=5},
                new Relationship { AnimalId=107, FoodId=8},
                new Relationship { AnimalId=108, FoodId=8},
                new Relationship { AnimalId=109, FoodId=8},
                new Relationship { AnimalId=109, FoodId=5}
            };

            relationships.ForEach(r => context.Relationships.Add(r));
            context.SaveChanges();
        }
    }
}